language: java
jdk:
  - oraclejdk8

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Denforcer.skip=true -B -V

after_success:
  - mvn clean verify -P integration-test
  - mvn clean test jacoco:report coveralls:report

sudo: false