language: java
jdk:
  - oraclejdk8

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Denforcer.skip=true -B -V
script: mvn test -Denforcer.skip=true -B

after_success:
  - mvn verify -P integration-test -Denforcer.skip=true
  - mvn clean verify coveralls:report -Denforcer.skip=true

sudo: false