pipeline:
  #annotators: "tokenize, ssplit, pos, lemma, ner, parse, dcoref"
  annotators: "tokenize, ssplit, pos, lemma, ner"

  pos:
    model: "edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger"
  ner:
    model: "edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz"
    useSUTime: false
    applyNumericClassifiers: false

  #parse_model: ""

logging:
  level: INFO
#  loggers:
#    "edu.stanford.nlp.ws.RequestResource": DEBUG

server:
  applicationConnectors:
    - type: http
      port: 7000
  adminConnectors:
    - type: http
      port: 7001
